import { Translation } from 'primeng/api';

/**
 * Libellés français des composants PrimeNG.
 *
 * `LOCALE_ID` ne couvre que les pipes Angular : les calendriers, filtres de
 * tableau et boîtes de confirmation tirent leurs textes d'ici.
 */
export const primeNgFr: Translation = {
    startsWith: 'Commence par',
    contains: 'Contient',
    notContains: 'Ne contient pas',
    endsWith: 'Se termine par',
    equals: 'Égal à',
    notEquals: 'Différent de',
    noFilter: 'Aucun filtre',
    lt: 'Inférieur à',
    lte: 'Inférieur ou égal à',
    gt: 'Supérieur à',
    gte: 'Supérieur ou égal à',
    is: 'Est',
    isNot: "N'est pas",
    before: 'Avant',
    after: 'Après',
    dateIs: 'Date égale à',
    dateIsNot: 'Date différente de',
    dateBefore: 'Date avant',
    dateAfter: 'Date après',
    clear: 'Effacer',
    apply: 'Appliquer',
    matchAll: 'Correspond à tout',
    matchAny: 'Correspond à au moins un',
    addRule: 'Ajouter une règle',
    removeRule: 'Supprimer la règle',
    accept: 'Oui',
    reject: 'Non',
    choose: 'Choisir',
    upload: 'Envoyer',
    cancel: 'Annuler',
    completed: 'Terminé',
    pending: 'En attente',
    dayNames: ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
    dayNamesShort: ['dim', 'lun', 'mar', 'mer', 'jeu', 'ven', 'sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    monthNamesShort: ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'],
    chooseYear: "Choisir l'année",
    chooseMonth: 'Choisir le mois',
    chooseDate: 'Choisir la date',
    prevDecade: 'Décennie précédente',
    nextDecade: 'Décennie suivante',
    prevYear: 'Année précédente',
    nextYear: 'Année suivante',
    prevMonth: 'Mois précédent',
    nextMonth: 'Mois suivant',
    prevHour: 'Heure précédente',
    nextHour: 'Heure suivante',
    prevMinute: 'Minute précédente',
    nextMinute: 'Minute suivante',
    prevSecond: 'Seconde précédente',
    nextSecond: 'Seconde suivante',
    am: 'am',
    pm: 'pm',
    today: "Aujourd'hui",
    weekHeader: 'Sem',
    // Lundi : premier jour de la semaine dans l'usage francophone.
    firstDayOfWeek: 1,
    dateFormat: 'dd/mm/yy',
    weak: 'Faible',
    medium: 'Moyen',
    strong: 'Fort',
    passwordPrompt: 'Saisissez un mot de passe',
    emptyMessage: 'Aucun résultat',
    searchMessage: '{0} résultats disponibles',
    selectionMessage: '{0} éléments sélectionnés',
    emptySelectionMessage: 'Aucun élément sélectionné',
    emptySearchMessage: 'Aucun résultat',
    emptyFilterMessage: 'Aucun résultat',
    fileSizeTypes: ['o', 'Ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo'],
    fileChosenMessage: '{0} fichiers',
    noFileChosenMessage: 'Aucun fichier choisi',
    aria: {
        trueLabel: 'Vrai',
        falseLabel: 'Faux',
        nullLabel: 'Non sélectionné',
        star: '1 étoile',
        stars: '{star} étoiles',
        selectAll: 'Tous les éléments sélectionnés',
        unselectAll: 'Tous les éléments désélectionnés',
        close: 'Fermer',
        previous: 'Précédent',
        next: 'Suivant',
        navigation: 'Navigation',
        scrollTop: 'Défiler en haut',
        moveTop: 'Déplacer tout en haut',
        moveUp: 'Déplacer vers le haut',
        moveDown: 'Déplacer vers le bas',
        moveBottom: 'Déplacer tout en bas',
        moveToTarget: 'Déplacer vers la cible',
        moveToSource: 'Déplacer vers la source',
        moveAllToTarget: 'Tout déplacer vers la cible',
        moveAllToSource: 'Tout déplacer vers la source',
        pageLabel: 'Page {page}',
        firstPageLabel: 'Première page',
        lastPageLabel: 'Dernière page',
        nextPageLabel: 'Page suivante',
        prevPageLabel: 'Page précédente',
        rowsPerPageLabel: 'Lignes par page',
        previousPageLabel: 'Page précédente',
        jumpToPageDropdownLabel: 'Aller à la page',
        jumpToPageInputLabel: 'Aller à la page',
        selectRow: 'Ligne sélectionnée',
        unselectRow: 'Ligne désélectionnée',
        expandRow: 'Ligne dépliée',
        collapseRow: 'Ligne repliée',
        showFilterMenu: 'Afficher le menu de filtre',
        hideFilterMenu: 'Masquer le menu de filtre',
        filterOperator: 'Opérateur de filtre',
        filterConstraint: 'Contrainte de filtre',
        editRow: 'Modifier la ligne',
        saveEdit: 'Enregistrer',
        cancelEdit: 'Annuler',
        listView: 'Vue en liste',
        gridView: 'Vue en grille',
        slide: 'Diapositive',
        slideNumber: 'Diapositive {slideNumber}',
        zoomImage: "Agrandir l'image",
        zoomIn: 'Agrandir',
        zoomOut: 'Réduire',
        rotateRight: 'Pivoter à droite',
        rotateLeft: 'Pivoter à gauche',
        listLabel: 'Liste déroulante'
    }
};
